# Generated by Django 2.0.2 on 2021-02-12 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0006_auto_20210212_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_post_pics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='blogposts.ImageAlbum'),
        ),
    ]
