# Generated by Django 2.0.2 on 2021-02-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0007_auto_20210212_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='album',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_post_pics',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageAlbum',
        ),
    ]
